apiVersion: v1
kind: ServiceAccount
metadata:
  name: stacksensor 
  namespace: kube-system
  labels:
    app.kubernetes.io/name: stacksensor
    app.kubernetes.io/part-of: stacksensor
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: stacksensor-clusterrole
  labels:
    app.kubernetes.io/name: stacksensor
    app.kubernetes.io/part-of: stacksensor
rules:
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - list
      - read
      - watch
  - apiGroups:
      - "apps"
    resources:
      - "*"
    verbs:
      - list
      - read
      - watch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "*"
    verbs:
      - list
      - read
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "*"
    verbs:
      - list
      - read
      - watch
  - apiGroups:
      - "policy"
    resources:
      - "*"
    verbs:
      - list
      - read
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: stacksensor-binding
  labels:
    app.kubernetes.io/name: stacksensor
    app.kubernetes.io/part-of: stacksensor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stacksensor-clusterrole
subjects:
  - kind: ServiceAccount
    name: stacksensor
    namespace: kube-system


